name = "round-boat-6c3d"            # ganti kalau mau nama lain
main = "worker.js"
compatibility_date = "2025-01-01"

account_id = "805fc4816dceeff5adcec1256d9888c"   # <-- GANTI dengan Cloudflare Account ID

kv_namespaces = [
  { binding = "AUTOPOST_KV", id = "46bb3f92ae3149cab7ae2124c78c9643" }  # <-- GANTI dengan KV Namespace ID
]
